package Vista;

import Cassandra.ConexionAstra;
import MongoFormulario.MongoFormularioMedico;
import MysqlFormulario.FormularioCursos;
import MysqlFormulario.FormularioEstudiantes;
import MysqlFormulario.FormularioNotas;
import PostgreSQL.FormularioCiclosYPagos;
import PostgreSQL.FormularioDeMatricula;
import Cassandra.FormularioAsistencia;

/**
 *
 * @author USER
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnCursos = new javax.swing.JButton();
        btnEstudiantes = new javax.swing.JButton();
        btnNotas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnWorkbeanch3 = new javax.swing.JButton();
        btnWorkbeanch4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnWorkbeanch5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnWorkbeanch6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnRegresar = new RSMaterialComponent.RSButtonMaterialIconDos();
        jLabel8 = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Notas y Cursos - MySQL Workbeanch", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCursos.setBackground(new java.awt.Color(255, 153, 153));
        btnCursos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCursos.setText("Cursos");
        btnCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCursosActionPerformed(evt);
            }
        });
        jPanel1.add(btnCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 99, 30));

        btnEstudiantes.setBackground(new java.awt.Color(255, 153, 153));
        btnEstudiantes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEstudiantes.setText("Estudiantes");
        btnEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstudiantesActionPerformed(evt);
            }
        });
        jPanel1.add(btnEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, 30));

        btnNotas.setBackground(new java.awt.Color(255, 153, 153));
        btnNotas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNotas.setText("Notas");
        btnNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotasActionPerformed(evt);
            }
        });
        jPanel1.add(btnNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 100, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("Ingresar Cursos:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 130, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setText("Ingresar Estudiantes:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 160, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ingresar Notas:");
        jLabel3.setToolTipText("");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 130, -1));

        jPanel5.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 340, 200));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Matricula y Pensiones- PostreSql", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnWorkbeanch3.setBackground(new java.awt.Color(153, 153, 255));
        btnWorkbeanch3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnWorkbeanch3.setText("Ciclos y Pagos");
        btnWorkbeanch3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWorkbeanch3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnWorkbeanch3, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 64, -1, -1));

        btnWorkbeanch4.setBackground(new java.awt.Color(153, 153, 255));
        btnWorkbeanch4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnWorkbeanch4.setText("Estudiantes");
        btnWorkbeanch4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWorkbeanch4ActionPerformed(evt);
            }
        });
        jPanel2.add(btnWorkbeanch4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 160, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ingresar Ciclos y Pagos:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 200, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ingresar Estudiantes:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 170, -1));

        jPanel5.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 330, 200));

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Ficha médica- Mongodb", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnWorkbeanch5.setBackground(new java.awt.Color(153, 255, 153));
        btnWorkbeanch5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnWorkbeanch5.setText("Formulario Médico");
        btnWorkbeanch5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWorkbeanch5ActionPerformed(evt);
            }
        });
        jPanel3.add(btnWorkbeanch5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Ingresar Formulario Médico:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 280, 30));

        jPanel5.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 340, 170));

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Asistencia-Casandra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnWorkbeanch6.setBackground(new java.awt.Color(255, 255, 102));
        btnWorkbeanch6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnWorkbeanch6.setText("Asistencia");
        btnWorkbeanch6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWorkbeanch6ActionPerformed(evt);
            }
        });
        jPanel4.add(btnWorkbeanch6, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 80, 130, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Registrar Asistencia:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 160, 30));

        jPanel5.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 330, 170));

        btnRegresar.setBackground(new java.awt.Color(153, 153, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.setBackgroundHover(new java.awt.Color(225, 71, 97));
        btnRegresar.setEffectButton(RSMaterialComponent.RSButtonMaterialIconDos.EFFECTBUTTON.RAISED);
        btnRegresar.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btnRegresar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.HOME);
        btnRegresar.setRound(25);
        btnRegresar.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                btnRegresarAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel5.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 170, 50));

        jLabel8.setBackground(new java.awt.Color(204, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPrincipalDeForm.png"))); // NOI18N
        jLabel8.setText("+");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 4));
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(714, 507));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCursosActionPerformed
        FormularioCursos form = new FormularioCursos();
        form.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCursosActionPerformed

    private void btnEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstudiantesActionPerformed
        FormularioEstudiantes fores = new FormularioEstudiantes();
        fores.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnEstudiantesActionPerformed

    private void btnNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotasActionPerformed
        FormularioNotas forno = new FormularioNotas();
        forno.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnNotasActionPerformed

    private void btnWorkbeanch3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorkbeanch3ActionPerformed
        FormularioCiclosYPagos Ciclo = new FormularioCiclosYPagos();
        Ciclo.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnWorkbeanch3ActionPerformed

    private void btnWorkbeanch4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorkbeanch4ActionPerformed
        FormularioDeMatricula matricula = new FormularioDeMatricula();
        matricula.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnWorkbeanch4ActionPerformed

    private void btnWorkbeanch5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorkbeanch5ActionPerformed
        MongoFormularioMedico mongo = new MongoFormularioMedico();
        mongo.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnWorkbeanch5ActionPerformed

    private void btnWorkbeanch6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorkbeanch6ActionPerformed
        new FormularioAsistencia().setVisible(true);
        dispose();

    }//GEN-LAST:event_btnWorkbeanch6ActionPerformed

    private void btnRegresarAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btnRegresarAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarAncestorMoved

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCursos;
    private javax.swing.JButton btnEstudiantes;
    private javax.swing.JButton btnNotas;
    private RSMaterialComponent.RSButtonMaterialIconDos btnRegresar;
    private javax.swing.JButton btnWorkbeanch3;
    private javax.swing.JButton btnWorkbeanch4;
    private javax.swing.JButton btnWorkbeanch5;
    private javax.swing.JButton btnWorkbeanch6;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
